services:
  mysql:
    image: mysql:8.0
    container_name: cinema_app_mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinemadb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - project_data:/var/lib/mysql

volumes:
  project_data: